RULES_BEGIN = SCREEN_END

rulesGrpPriority =	RULES_BEGIN
rulesGrpLo =		RULES_BEGIN + $00D4
rulesGrpHi =		RULES_BEGIN + $00E2 
rulesGrpSqrs0 =		RULES_BEGIN + $00F0
rulesGrpSqrs1 = 	RULES_BEGIN + $00FE
rulesGrpSqrs2 = 	RULES_BEGIN + $010C
rulesSqr0 = 		RULES_BEGIN + $0362
rulesSqrStrsLo = 	RULES_BEGIN + $03B2
rulesSqrStrsHi =	RULES_BEGIN + $03BA
rulesChestStrsLo = 	RULES_BEGIN + $0412
rulesChestStrsHi = 	RULES_BEGIN + $0422
rulesChest0 = 		RULES_BEGIN + $04F2
rulesChanceStrsLo =	RULES_BEGIN + $0512
rulesChanceStrsHi = 	RULES_BEGIN + $0522
rulesChance0 =		RULES_BEGIN + $05F2
rulesGrpPointsFull = 	RULES_BEGIN + $0612
rulesGrpPointsPart = 	RULES_BEGIN + $0620

RULES_END = RULES_BEGIN + $062E